# Generated by Django 4.0.4 on 2022-05-30 16:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название товара')),
                ('price', models.PositiveIntegerField(default=1, verbose_name='Кол-во товара')),
                ('count', models.PositiveIntegerField(default=1, verbose_name='Цена')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата')),
                ('count', models.PositiveIntegerField(verbose_name='Кол-во товара')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='basket.product')),
            ],
        ),
    ]
