# Generated by Django 4.0.4 on 2022-05-30 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0003_remove_product_count_cart_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='count',
            field=models.PositiveIntegerField(default=1, verbose_name='Кол-во товара'),
        ),
    ]
