# Generated by Django 4.0.4 on 2022-05-31 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0004_product_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=123, upload_to='upload/'),
            preserve_default=False,
        ),
    ]
