# Generated by Django 4.0.4 on 2022-06-01 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0010_alter_cart_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='cart',
            name='sum_price',
            field=models.PositiveIntegerField(default=1, verbose_name='Сумма'),
        ),
    ]
