# Generated by Django 4.0.4 on 2022-06-04 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0011_remove_product_image_cart_sum_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum_price', models.PositiveIntegerField(default=1, verbose_name='Сумма заказа')),
            ],
        ),
        migrations.RemoveField(
            model_name='cart',
            name='sum_price',
        ),
    ]
