# Generated by Django 4.0.4 on 2022-06-04 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0012_ordercart_remove_cart_sum_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='basket.ordercart', verbose_name='Номер заказа'),
            preserve_default=False,
        ),
    ]
