# Generated by Django 4.0.4 on 2022-06-04 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0013_cart_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='order',
        ),
        migrations.AddField(
            model_name='cart',
            name='sum_price',
            field=models.PositiveIntegerField(default=1, verbose_name='Сумма'),
        ),
        migrations.DeleteModel(
            name='OrderCart',
        ),
    ]
