# Generated by Django 4.0.4 on 2022-06-04 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0017_order_remove_cart_sum_price_cart_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='order',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
