# Generated by Django 4.0.4 on 2022-06-04 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0019_cart_sum_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
    ]
