# Generated by Django 4.0.4 on 2022-06-04 21:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0020_alter_product_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum_price', models.PositiveIntegerField(default=1, verbose_name='Сумма')),
            ],
        ),
        migrations.RemoveField(
            model_name='cart',
            name='sum_price',
        ),
        migrations.AddField(
            model_name='cart',
            name='order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='basket.order', verbose_name='Номер заказа'),
            preserve_default=False,
        ),
    ]
