# Generated by Django 4.0.4 on 2022-06-04 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0021_order_remove_cart_sum_price_cart_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='sum_price',
            field=models.PositiveIntegerField(default=1, verbose_name='стоимость'),
        ),
    ]
