# Generated by Django 4.0.4 on 2022-06-04 23:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0022_cart_sum_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='sum_price',
        ),
    ]
